apiVersion: v2
name: remark42
description: A Helm chart for Remark42 comment system

type: application

maintainers:
  - name: groundhog2k

version: "0.7.1"

appVersion: "v1.13.1"

dependencies:
  - name: redis
    version: "0.6.14"
    repository: "https://groundhog2k.github.io/helm-charts"
    condition: redis.enabled
